import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";



export default function Home() {
  return (
    <>
      <Head>
        <title>Web3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>helo</h3>
    </>
  );
}
